version: "3.7"
services:
  app:
    build:
      args:
        user: shabayek
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: docker-laravel
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file:
      - ./src/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homestead}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    image: composer:2
    container_name: composer
    working_dir: /var/www/html
    depends_on:
      - app
    entrypoint: ['composer', '--ignore-platform-reqs']
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  npm:
    image: node:16.13
    container_name: npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      args:
        user: shabayek
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      
networks:
  laravel:
    driver: bridge
