version: "3.7"
services:
  app:
    build:
      args:
        user: shabayek
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: docker-laravel
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel

  composer:
    image: composer:2
    container_name: composer
    working_dir: /var/www/html
    depends_on:
      - app
    entrypoint: ['composer', '--ignore-platform-reqs']
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  npm:
    image: node:16.13
    container_name: npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
      
networks:
  laravel:
    driver: bridge
